name: custom_signature
description: This package project offers an easy way to get your signature with
  a custom UI, and rotates automatically into landscape mode for most
  comfortable space to sign.
version: 1.0.3
homepage: https://github.com/ma-sc-24/custom_signature

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  signature: ^5.3.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter: null

# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware

fonts:
  - family: IBMPlexSans
    fonts:
      - asset: packages/custom_signature/fonts/IBMPlexSans-Regular.ttf
      - asset: packages/custom_signature/fonts/IBMPlexSans-SemiBold.ttf
        weight: 600
